version: '3'
services:
  mongo:
    image: mongo
    environment: 
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/logs
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/logs:/data/logs
    ports:
      - 27017:27017