version: '3'
services:
  app:
    build: .
    environment:
      MONGO_NAME: mongo
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment: 
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/logs
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/logs:/data/logs
    ports:
      - 27017:27017